services:
  # Flask servers
  flask_server1:
    # https://docs.docker.com/reference/compose-file/build/
    image: flask_app    # local build
    environment:
      FLASK_PORT: 5000
      SERVER_NAME: "Flask Server 1"

  flask_server2:
    image: flask_app
    environment:
      FLASK_PORT: 5000
      SERVER_NAME: "Flask Server 2"

  flask_server3:
    image: flask_app
    environment:
      FLASK_PORT: 5000
      SERVER_NAME: "Flask Server 3"

  # Nginx for load balancing
  nginx:
    image: nginx:1.27
    volumes:
      # https://docs.docker.com/reference/compose-file/services/#short-syntax-5
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_server1
      - flask_server2
      - flask_server3
